### ISSUE TITLE
Sqlite db error on attempt to re-open closed objects

### ISSUE THREAD

**Issue by goodmeow** [joshuous/JankBenchX#5]
time: 1618964105728
msg: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.android.benchmark/databases/BenchmarkResults
stacktrace: java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.android.benchmark/databases/BenchmarkResults
	at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:58)
	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1396)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1272)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1440)
	at com.android.benchmark.results.GlobalResultsStore.loadRefreshRate(GlobalResultsStore.java:316)
	at com.android.benchmark.results.GlobalResultsStore.loadDetailedAggregatedResults(GlobalResultsStore.java:377)
	at com.android.benchmark.api.JankBenchAPI.createEntry(JankBenchAPI.java:64)
	at com.android.benchmark.api.JankBenchAPI.uploadResults(JankBenchAPI.java:30)
	at com.android.benchmark.app.RunLocalBenchmarksActivity$3.doInBackground(RunLocalBenchmarksActivity.java:311)
	at com.android.benchmark.app.RunLocalBenchmarksActivity$3.doInBackground(RunLocalBenchmarksActivity.java:299)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by joshchoo** [comment]
Which version of JankBenchX does it happen on?

**Comment by goodmeow** [comment]
> Which version of JankBenchX does it happen on?

2.2.0 , it happened when i tried to upload the result

**Comment by Tokankiz** [comment]
> time: 1618964105728
> msg: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.android.benchmark/databases/BenchmarkResults
> stacktrace: java.lang.RuntimeException: An error occurred while executing doInBackground()
> at android.os.AsyncTask$4.done(AsyncTask.java:415)
> at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
> at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
> at java.util.concurrent.FutureTask.run(FutureTask.java:271)
> at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:923)
> Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.android.benchmark/databases/BenchmarkResults
> at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:58)
> at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1396)
> at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1272)
> at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1440)
> at com.android.benchmark.results.GlobalResultsStore.loadRefreshRate(GlobalResultsStore.java:316)
> at com.android.benchmark.results.GlobalResultsStore.loadDetailedAggregatedResults(GlobalResultsStore.java:377)
> at com.android.benchmark.api.JankBenchAPI.createEntry(JankBenchAPI.java:64)
> at com.android.benchmark.api.JankBenchAPI.uploadResults(JankBenchAPI.java:30)
> at com.android.benchmark.app.RunLocalBenchmarksActivity$3.doInBackground(RunLocalBenchmarksActivity.java:311)
> at com.android.benchmark.app.RunLocalBenchmarksActivity$3.doInBackground(RunLocalBenchmarksActivity.java:299)
> at android.os.AsyncTask$3.call(AsyncTask.java:394)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> ... 4 more
